'use client'

import { useTranslations } from 'next-intl'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { useJournal } from '@/hooks/accounting'
import LoadingSpinner from '@/components/ui/LoadingSpinner'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'

interface JournalDetailClientProps {
  journalId: string
  locale: string
}

/**
 * 金額格式化
 */
function formatAmount(amount: number | null | undefined): string {
  return `NT$ ${(amount || 0).toLocaleString('zh-TW', { maximumFractionDigits: 0 })}`
}

/**
 * 傳票詳情客戶端元件
 */
export default function JournalDetailClient({ journalId, locale }: JournalDetailClientProps) {
  const t = useTranslations()
  const router = useRouter()
  const { data: journal, isLoading, error } = useJournal(journalId)

  if (isLoading) {
    return (
      <Card>
        <CardContent className="flex justify-center items-center py-12">
          <LoadingSpinner data-testid="loading-spinner" />
        </CardContent>
      </Card>
    )
  }

  if (error || !journal) {
    return (
      <Card>
        <CardContent className="p-6 text-center text-destructive">
          {t('common.error')}: {error?.message || t('common.notFound')}
        </CardContent>
      </Card>
    )
  }

  const getStatusBadge = (status: string) => {
    const variants: Record<string, 'outline' | 'secondary' | 'default' | 'destructive'> = {
      DRAFT: 'outline',
      POSTED: 'default',
      VOIDED: 'destructive',
    }
    const statusMap: Record<string, string> = {
      DRAFT: 'draft',
      POSTED: 'posted',
      VOIDED: 'voided',
    }
    return (
      <Badge variant={variants[status] || 'outline'}>
        {t(`accounting.status.${statusMap[status] || status.toLowerCase()}`)}
      </Badge>
    )
  }

  const getSourceBadge = (source: string) => {
    const sourceMap: Record<string, string> = {
      MANUAL: 'manual',
      INVOICE: 'invoice',
      BANK: 'bank',
      ADJUSTMENT: 'adjustment',
    }
    return (
      <Badge variant="secondary">
        {t(`accounting.journalSource.${sourceMap[source] || source.toLowerCase()}`)}
      </Badge>
    )
  }

  // 計算借貸合計
  const transactions = journal.transactions || []
  const totalDebit = transactions.reduce((sum, tx) => sum + (tx.debit || 0), 0)
  const totalCredit = transactions.reduce((sum, tx) => sum + (tx.credit || 0), 0)
  const isBalanced = Math.abs(totalDebit - totalCredit) < 0.01

  return (
    <div className="space-y-6">
      {/* 標頭與返回按鈕 */}
      <div className="flex items-center justify-between">
        <Button variant="ghost" onClick={() => router.back()}>
          ← {t('common.back')}
        </Button>
      </div>

      {/* 傳票基本資訊 */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="text-2xl">{journal.journal_number}</CardTitle>
              <CardDescription>
                {new Date(journal.date).toLocaleDateString('zh-TW')}
              </CardDescription>
            </div>
            <div className="flex gap-2">
              {getSourceBadge(journal.source_type)}
              {getStatusBadge(journal.status)}
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* 描述 */}
            <div className="md:col-span-2">
              <h3 className="text-sm font-medium text-muted-foreground mb-2">
                {t('accounting.journals.description')}
              </h3>
              <p>{journal.description || '-'}</p>
            </div>

            {/* 來源發票連結 */}
            {journal.invoice_id && (
              <div>
                <h3 className="text-sm font-medium text-muted-foreground mb-2">
                  {t('accounting.journals.sourceInvoice')}
                </h3>
                <Button variant="link" className="p-0 h-auto" asChild>
                  <Link href={`/${locale}/accounting/invoices/${journal.invoice_id}`}>
                    {t('accounting.journals.viewInvoice')}
                  </Link>
                </Button>
              </div>
            )}

            {/* 自動產生標記 */}
            {journal.is_auto_generated && (
              <div>
                <Badge variant="outline" className="text-xs">
                  {t('accounting.journals.autoGenerated')}
                </Badge>
              </div>
            )}
          </div>
        </CardContent>
      </Card>

      {/* 分錄明細 */}
      <Card>
        <CardHeader>
          <CardTitle>{t('accounting.journals.transactions')}</CardTitle>
          <CardDescription>
            {isBalanced ? (
              <span className="text-green-600">{t('accounting.journals.balanced')}</span>
            ) : (
              <span className="text-red-600">{t('accounting.journals.unbalanced')}</span>
            )}
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>{t('accounting.journals.accountCode')}</TableHead>
                <TableHead>{t('accounting.journals.accountName')}</TableHead>
                <TableHead>{t('accounting.journals.transactionDescription')}</TableHead>
                <TableHead className="text-right">{t('accounting.journals.debit')}</TableHead>
                <TableHead className="text-right">{t('accounting.journals.credit')}</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {transactions.map((tx, index) => (
                <TableRow key={tx.id || index}>
                  <TableCell className="font-mono">
                    {tx.account?.code || '-'}
                  </TableCell>
                  <TableCell>
                    {tx.account?.name || '-'}
                  </TableCell>
                  <TableCell className="text-muted-foreground">
                    {tx.description || '-'}
                  </TableCell>
                  <TableCell className="text-right font-medium">
                    {tx.debit > 0 ? formatAmount(tx.debit) : '-'}
                  </TableCell>
                  <TableCell className="text-right font-medium">
                    {tx.credit > 0 ? formatAmount(tx.credit) : '-'}
                  </TableCell>
                </TableRow>
              ))}
              {/* 合計列 */}
              <TableRow className="font-bold border-t-2">
                <TableCell colSpan={3} className="text-right">
                  {t('accounting.journals.total')}
                </TableCell>
                <TableCell className="text-right">
                  {formatAmount(totalDebit)}
                </TableCell>
                <TableCell className="text-right">
                  {formatAmount(totalCredit)}
                </TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      {/* 過帳資訊 */}
      {journal.status === 'POSTED' && journal.posted_at && (
        <Card>
          <CardHeader>
            <CardTitle>{t('accounting.journals.postingInfo')}</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <h3 className="text-sm font-medium text-muted-foreground mb-1">
                  {t('accounting.journals.postedAt')}
                </h3>
                <p className="font-medium">
                  {new Date(journal.posted_at).toLocaleString('zh-TW')}
                </p>
              </div>
              {journal.posted_by && (
                <div>
                  <h3 className="text-sm font-medium text-muted-foreground mb-1">
                    {t('accounting.journals.postedBy')}
                  </h3>
                  <p className="font-medium">{journal.posted_by}</p>
                </div>
              )}
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  )
}
